# Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
  joint_model_group: moveo_arm
  joint_model_group_pose: home
# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - Joint_1
    - Joint_2
    - Joint_3
    - Joint_4
    - Joint_5
    - Gripper_Idol_Gear_Joint
    - Gripper_Servo_Gear_Joint
  sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
controller_list:
  []
arm_position_controller:
  type: position_controllers/JointPositionController
  joints:
    - Joint_1
    - Joint_2
    - Joint_3
    - Joint_4
    - Joint_5
  gains:
    Joint_1:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    Joint_2:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    Joint_3:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    Joint_4:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    Joint_5:
      p: 100
      d: 1
      i: 1
      i_clamp: 1